trigger:
- master

pool:
 vmImage: ubuntu-latest

stages:
# - stage: Build
#   jobs:
#   - job: Build Project
#     steps:

#       - task: NodeTool@0
#         inputs: 
#           versionSpec: '22.x'

#       - script: npm install
#         displayName: Install Dependencies

#       - script: npm

- stage: Test
  jobs:
  - job: TestProject
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '22.x'

    - script: npm install
      displayName: Install Dependencies

    - script: npm test:coverage
      displayName: Run Unit Tests and Code Coverage 

    - task: PublishTestResults@2
      inputs:
        testResultsFormat: JUnit
        testResultsFiles: junit.xml
        failTaskOnFailedTests: true

    - task: PublishCodeCoverageResults@2
      inputs:
        codeCoverageTool: Cobertura
        summaryFileLocation: 'coverage/cobertura-coverage.xml'
